version: '3.7'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  postgres:
  redis:
    driver: local
